### ISSUE TITLE
TeamSignIn HibernateOptimisticLockingFailure

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#115]
Looks like threading issue.

username: studentuser
url: http://wise.berkeley.edu:80/webapp/student/teamsignin.html?runId=somerunId

exception message: org.springframework.orm.hibernate3.HibernateOptimisticLockingFailureException: Object of class [net.sf.sail.webapp.domain.group.impl.PersistentGroup] with identifier [109150]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [net.sf.sail.webapp.domain.group.impl.PersistentGroup#109150]

stacktrace:
org.springframework.orm.hibernate3.HibernateOptimisticLockingFailureException: Object of class [net.sf.sail.webapp.domain.group.impl.PersistentGroup] with identifier [109150]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [net.sf.sail.webapp.domain.group.impl.PersistentGroup#109150]
        at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:672)
        at org.springframework.orm.hibernate3.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:793)
        at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:664)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:393)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at $Proxy47.addStudentToRun(Unknown Source)
        at org.telscenter.sail.webapp.presentation.web.controllers.student.TeamSignInController.onSubmit(TeamSignInController.java:156)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [net.sf.sail.webapp.domain.group.impl.PersistentGroup#109150]

**Comment by geoffreykwan** [comment]
We'll see if this fixes the problem once we update the server.
https://github.com/WISE-Community/WISE-Portal/commit/d28db13e453a3d5c56aec8c78c9e78e3a322d286

**Comment by hirokiterashima** [comment]
We're still seeing this exception.

Moved to 4.8 release
