### ISSUE TITLE
ClassNotFoundException: org.quartz.ee.servlet.QuartzInitializerListener

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#75]
this goes away when i clean tomcat and republish, but it seems to come back when I restart computer&eclipse, so find a cure.

Nov 27, 2012 10:33:04 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: .:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
Nov 27, 2012 10:33:04 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.j2ee.server:vlewrapper' did not find a matching property.
Nov 27, 2012 10:33:04 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.j2ee.server:webapp' did not find a matching property.
Nov 27, 2012 10:33:04 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Nov 27, 2012 10:33:04 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Nov 27, 2012 10:33:04 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 633 ms
Nov 27, 2012 10:33:04 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Nov 27, 2012 10:33:04 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.32
Nov 27, 2012 10:33:05 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class org.quartz.ee.servlet.QuartzInitializerListener
java.lang.ClassNotFoundException: org.quartz.ee.servlet.QuartzInitializerListener
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:05 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Skipped installing application listeners due to previous error(s)
Nov 27, 2012 10:33:05 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 27, 2012 10:33:05 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/vlewrapper] startup failed due to previous errors
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class org.springframework.web.util.Log4jConfigListener
java.lang.ClassNotFoundException: org.springframework.web.util.Log4jConfigListener
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class net.sf.sail.webapp.spring.impl.CustomContextLoaderListener
java.lang.ClassNotFoundException: net.sf.sail.webapp.spring.impl.CustomContextLoaderListener
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class net.sf.sail.webapp.presentation.web.listeners.PasSessionListener
java.lang.ClassNotFoundException: net.sf.sail.webapp.presentation.web.listeners.PasSessionListener
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Error configuring application listener of class org.springframework.security.web.session.HttpSessionEventPublisher
java.lang.ClassNotFoundException: org.springframework.security.web.session.HttpSessionEventPublisher
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:532)
    at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:514)
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:133)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Skipped installing application listeners due to previous error(s)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Nov 27, 2012 10:33:06 AM org.apache.catalina.session.StandardManager doLoad
SEVERE: ClassNotFoundException while loading persisted sessions: java.lang.ClassNotFoundException: net.sf.sail.webapp.domain.impl.UserImpl
java.lang.ClassNotFoundException: net.sf.sail.webapp.domain.impl.UserImpl
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.apache.catalina.util.CustomObjectInputStream.resolveClass(CustomObjectInputStream.java:76)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1574)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1495)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1731)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1595)
    at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1060)
    at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:284)
    at org.apache.catalina.session.StandardManager.load(StandardManager.java:204)
    at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:491)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5294)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.session.StandardManager startInternal
SEVERE: Exception loading sessions from persistent storage
java.lang.ClassNotFoundException: net.sf.sail.webapp.domain.impl.UserImpl
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.apache.catalina.util.CustomObjectInputStream.resolveClass(CustomObjectInputStream.java:76)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1574)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1495)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1731)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1595)
    at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1060)
    at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:284)
    at org.apache.catalina.session.StandardManager.load(StandardManager.java:204)
    at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:491)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5294)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/webapp] startup failed due to previous errors
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/curriculum
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/docs
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/examples
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Nov 27, 2012 10:33:06 AM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('org.apache.jasper.compiler.TldLocationsCache', 'org.apache.jasper.compiler.TldLocationsCache@636f2067')
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/host-manager
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/manager
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/ROOT
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /Users/h/catalina_base_eclipse/webapps/studentuploads
Nov 27, 2012 10:33:06 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Nov 27, 2012 10:33:06 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Nov 27, 2012 10:33:06 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 1761 ms

**Comment by hirokiterashima** [comment]
what the catalina_home/webapps/webapp/WEB-INF/lib looks like

### START COMPUTER, OPEN ECLIPSE, BEFORE CLEANING TOMCAT

webapp h$ cd WEB-INF/lib/

lib h$ ls
antlr-2.7.6.jar                 dom4j-1.6.1.jar                 logkit-1.0.1.jar
asm-1.5.3.jar                   ecore-2.2.0.jar                 mysql-connector-java-5.1.21.jar
asm-attrs-1.5.3.jar             ehcache-1.3.0.jar               nekohtml-0.9.5.jar
avalon-framework-4.1.3.jar          h2-1.0.20070429.jar             pas-curnitmap-0.1.0-SNAPSHOT.jar
camel-core-1.5.0.jar                hibernate-3.2.6.ga.jar              qti-bindings-2.0-SNAPSHOT.jar
cglib-2.1_3.jar                 hibernate-annotations-3.4.0.GA.jar      sail-core-0.4.5-SNAPSHOT.jar
common-2.2.0.jar                hibernate-commons-annotations-3.1.0.GA.jar  sail-data-emf-0.1.0-SNAPSHOT.jar
commons-collections-3.2.jar         hsqldb-1.8.0.7.jar              slf4j-api-1.5.2.jar
commons-dbcp-1.2.1.jar              httpunit-1.7.jar                slf4j-log4j12-1.5.2.jar
commons-io-2.4.jar              jta-1.0.1B.jar                  xercesImpl-2.0.2.jar
commons-lang-2.2.jar                jtidy-4aug2000r7-dev.jar            xml-apis-1.0.b2.jar
commons-logging-1.1.jar             jug-1.1.2.jar
commons-pool-1.2.jar                log4j-1.2.13.jar

### AFTER CLEANING TOMCAT

lib h$ ls
activation-1.1.jar              ejb3-persistence-1.0.2.GA.jar           quartz-1.5.1.jar
antlr-2.7.6.jar                 geronimo-stax-api_1.0_spec-1.0.jar      recaptcha4j-0.0.7.jar
aopalliance-1.0.jar             h2-1.0.20070429.jar             sail-core-0.4.5-SNAPSHOT.jar
asm-1.5.3.jar                   hibernate-3.2.6.ga.jar              sail-data-emf-0.1.0-SNAPSHOT.jar
asm-attrs-1.5.3.jar             hibernate-annotations-3.4.0.GA.jar      slf4j-api-1.5.2.jar
aspectjrt-1.5.3.jar             hibernate-commons-annotations-3.1.0.GA.jar  slf4j-log4j12-1.5.2.jar
avalon-framework-4.1.3.jar          hibernate-core-3.3.0.SP1.jar            spring-aop-3.0.5.RELEASE.jar
axis-1.4.jar                    hsqldb-1.8.0.7.jar              spring-asm-3.0.5.RELEASE.jar
axis-jaxrpc-1.4.jar             httpunit-1.7.jar                spring-aspects-3.0.5.RELEASE.jar
axis-saaj-1.4.jar               icu4j-49.1.jar                  spring-beans-3.0.5.RELEASE.jar
axis-wsdl4j-1.5.1.jar               itext-1.3.jar                   spring-context-3.0.5.RELEASE.jar
backport-util-concurrent-3.0.jar        jaxb-api-2.0.jar                spring-context-support-3.0.5.RELEASE.jar
camel-core-1.5.0.jar                jaxb-impl-2.0.3.jar             spring-core-3.0.5.RELEASE.jar
cglib-2.1_3.jar                 jaxen-1.1.4.jar                 spring-expression-3.0.5.RELEASE.jar
common-2.2.0.jar                jdom-1.1.jar                    spring-jdbc-3.0.5.RELEASE.jar
commons-beanutils-1.7.0.jar         jsr107cache-1.0.jar             spring-orm-3.0.5.RELEASE.jar
commons-codec-1.3.jar               jsr173_api-1.0.jar              spring-security-acl-3.1.1.RELEASE.jar
commons-collections-3.2.jar         jstl-1.1.2.jar                  spring-security-config-3.1.1.RELEASE.jar
commons-dbcp-1.2.1.jar              jta-1.0.1B.jar                  spring-security-core-3.1.1.RELEASE.jar
commons-discovery-0.2.jar           jtidy-4aug2000r7-dev.jar            spring-security-core-tiger-2.0.7.RELEASE.jar
commons-fileupload-1.2.1.jar            jug-1.1.2.jar                   spring-security-taglibs-3.1.1.RELEASE.jar
commons-httpclient-3.0.1.jar            log4j-1.2.13.jar                spring-security-web-3.1.1.RELEASE.jar
commons-io-2.4.jar              logkit-1.0.1.jar                spring-test-3.0.5.RELEASE.jar
commons-lang-2.2.jar                mail-1.4.jar                    spring-tx-3.0.5.RELEASE.jar
commons-logging-1.1.jar             mysql-connector-java-5.1.21.jar         spring-web-3.0.5.RELEASE.jar
commons-pool-1.2.jar                nekohtml-0.9.5.jar              spring-webmvc-3.0.5.RELEASE.jar
displaytag-1.1.jar              pas-curnitmap-0.1.0-SNAPSHOT.jar        standard-1.1.2.jar
dom4j-1.6.1.jar                 poi-3.7.jar                 stax-api-1.0.1.jar
dwr-2.0.1.jar                   poi-ooxml-3.7.jar               xercesImpl-2.0.2.jar
ecore-2.2.0.jar                 poi-ooxml-schemas-3.7.jar           xml-apis-1.0.b2.jar
ehcache-1.3.0.jar               qti-bindings-2.0-SNAPSHOT.jar           xmlbeans-2.4.0.jar
