### ISSUE TITLE
exception when creating new teacher account

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Portal--Deprecated--#92]
not a showstopper, but prevents email from being sent to teacher.

Exception in thread "Thread-15" org.springframework.context.NoSuchMessageException: No message found under code 'welcome.new.teacher.subject' for locale 'en_US'.
    at org.springframework.context.support.AbstractMessageSource.getMessage(AbstractMessageSource.java:135)
    at org.telscenter.sail.webapp.presentation.web.controllers.teacher.RegisterTeacherController$NewAccountEmailService.sendEmail(RegisterTeacherController.java:215)
    at org.telscenter.sail.webapp.presentation.web.controllers.teacher.RegisterTeacherController$NewAccountEmailService.run(RegisterTeacherController.java:194)
    at java.lang.Thread.run(Thread.java:619)

**Comment by hirokiterashima** [comment]
fixed, committed
https://github.com/WISE-Community/WISE-Portal/commit/618b1f2e0dc1028cf949ce02d7f7c558dce108d8
